require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

Metrics/LineLength:
  Max: 120
Documentation:
  Enabled: false

Style/PercentQLiterals:
  EnforcedStyle: upper_case_q

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
