version: '3.8'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: wishlist
    ports:
      - "3306:3306"
  app:
    build:
      context: .
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      WISHLIST_DATABASE_PASSWORD: wishlist
      WISHLIST_DATABASE_USER: "root"
    entrypoint: sh -c "./dockerize -timeout 60s -wait tcp://mysql:3306 bin/rake db:drop && bin/rake db:create && bin/rake db:migrate && bin/rails s -b 0.0.0.0"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
